# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Spell
  description: Spelling Microservice
  version: "1.0.0"
# the domain of the service
host: despina.128.no
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /
produces:
  - application/json
paths:
  /spell:
   post:
      summary: Provide completion or spelling correction suggestions.
      description: |
        Specify whether completion or correction of query is desired.
        
        Given a query of a single word, returns a list of suggestions.
      parameters:
        - name: Type
          in: formData
          description: Either 'completion' or 'correction'
          required: true
          type: string
        - name: Query
          in: formData
          description: A single query word to correct or complete, depending on Type-flag. 
          required: true
          type: string
        - name: Search
          in: formData
          description: Is the spelling correction for a search term? 
                       (if yes, specialized frequency lists will be used, rather than generic ones).
          required: true
          type: boolean
      responses:
        200:
          description: A list of results
          schema:
            type: array
            items:
              $ref: '#/definitions/spelling'
definitions:
  spelling:
    type: string
    description: a single word, a suggestion for completion/correction

